---
# Base system setup - Essential packages and user configuration
# This role sets up the foundation that all other roles depend on

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: ["base", "packages"]

- name: Install essential base packages
  apt:
    name: "{{ base_packages }}"
    state: present
  tags: ["base", "packages"]

- name: Add user to video group (for GPU access)
  user:
    name: "{{ target_user }}"
    groups: video
    append: yes
  tags: ["base", "user"]

- name: Configure passwordless sudo for target user
  lineinfile:
    path: /etc/sudoers.d/{{ target_user }}
    line: "{{ target_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
    create: yes
    mode: '0440'
    validate: 'visudo -cf %s'
  tags: ["base", "sudo"]

- name: Set up git configuration
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.email", value: "{{ target_email }}" }
    - { name: "user.name", value: "{{ target_name }}" }
  become: no
  tags: ["base", "git"]

- name: Change default shell to zsh
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh
  tags: ["base", "shell"]

- name: Configure PAM environment variables
  copy:
    src: "{{ playbook_dir }}/../system/etc/security/pam_env.conf"
    dest: /etc/security/pam_env.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: ["base", "environment"]

- name: Create essential directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  loop:
    - "{{ target_home }}/.local/bin"
    - "{{ target_home }}/.config"
    - "{{ target_home }}/Downloads/git"
  become: no
  tags: ["base", "directories"]

- name: Install interception tools for caps2esc
  block:
    - name: Check if interception-caps2esc is available in main repos
      shell: apt-cache search interception-caps2esc
      register: interception_available
      changed_when: false
      failed_when: false
      
    - name: Install interception-caps2esc from main repos if available
      apt:
        name: interception-caps2esc
        state: present
      when: "'interception-caps2esc' in interception_available.stdout"
      
    - name: Install build dependencies for interception tools
      apt:
        name:
          - build-essential
          - cmake
          - libudev-dev
          - libevdev-dev
        state: present
      when: "'interception-caps2esc' not in interception_available.stdout"
      
    - name: Clone interception-tools repository
      git:
        repo: https://gitlab.com/interception/linux/tools.git
        dest: /tmp/interception-tools
        force: yes
      when: "'interception-caps2esc' not in interception_available.stdout"
      
    - name: Build and install interception-tools
      shell: |
        cd /tmp/interception-tools
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build
      when: "'interception-caps2esc' not in interception_available.stdout"
      
    - name: Clone caps2esc repository
      git:
        repo: https://gitlab.com/interception/linux/plugins/caps2esc.git
        dest: /tmp/caps2esc
        force: yes
      when: "'interception-caps2esc' not in interception_available.stdout"
      
    - name: Build and install caps2esc
      shell: |
        cd /tmp/caps2esc
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build
      when: "'interception-caps2esc' not in interception_available.stdout"
      
    - name: Clean up build directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/interception-tools
        - /tmp/caps2esc
      when: "'interception-caps2esc' not in interception_available.stdout"
      
  tags: ["base", "interception"]
