#!/bin/bash
# Wrapper script to show dotfiles-sync status in floating kitty terminal

kitty --app-id=git_sync_float -e sh -c '/home/bgo/.local/bin/dotfiles-sync --status; echo ""; read -p "Press enter to close..."'
