#!/bin/bash
# Wrapper script to run dotfiles-sync in floating kitty terminal

# Make sure we're in a proper environment
export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"

# Launch kitty in background
kitty --app-id=git_sync_float -e /home/bgo/.local/bin/dotfiles-sync &
